# Generated by Django 4.2.4 on 2023-08-21 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kakaoUsers',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=255, null=True)),
                ('user_coin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('regions', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('kms', models.FloatField(null=True)),
                ('stacks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='saveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnedCoin', models.IntegerField(default=0)),
                ('info', models.JSONField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwg.kakaousers')),
            ],
        ),
    ]
