# Generated by Django 4.2.4 on 2023-08-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('regions', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('kms', models.IntegerField(null=True)),
                ('stacks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('user_pw', models.CharField(max_length=255, null=True)),
                ('user_email', models.EmailField(max_length=255, null=True)),
                ('user_coin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('records_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=255, null=True)),
                ('end_location', models.CharField(max_length=255, null=True)),
                ('TIME', models.TimeField(null=True)),
                ('feedback', models.CharField(max_length=255, null=True)),
                ('credits_earned', models.IntegerField(null=True)),
                ('record_date', models.DateTimeField(null=True)),
                ('data_valid', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], null=True)),
                ('km', models.IntegerField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwg.users')),
            ],
        ),
        migrations.CreateModel(
            name='Markings',
            fields=[
                ('AutoField', models.AutoField(primary_key=True, serialize=False)),
                ('marking_number', models.IntegerField(null=True)),
                ('records_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markings_records', to='wwg.records')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markings_user', to='wwg.users')),
            ],
        ),
    ]
