# Generated by Django 4.2.4 on 2023-08-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecords',
            fields=[
                ('marking_numb', models.AutoField(primary_key=True, serialize=False)),
                ('search_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_pw',
        ),
    ]
