# Generated by Django 4.2.4 on 2023-08-15 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='kms',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='saveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startpoint', models.JSONField()),
                ('endpoint', models.JSONField()),
                ('startName', models.TextField()),
                ('endName', models.TextField()),
                ('AtTime', models.IntegerField()),
                ('km', models.FloatField()),
                ('earned_coin', models.IntegerField(default=10)),
                ('coords', models.JSONField()),
                ('data_valid', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], null=True)),
                ('markings', models.JSONField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwg.kakaousers')),
            ],
        ),
    ]
