# Generated by Django 4.2.4 on 2023-08-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kakaoUsers',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=255, null=True)),
                ('user_coin', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='markings',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markings_user', to='wwg.kakaousers'),
        ),
        migrations.AlterField(
            model_name='records',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwg.kakaousers'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
