# Generated by Django 4.2.4 on 2023-08-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwg', '0002_searchrecords_remove_users_user_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='kakaoUsers',
        ),
    ]
