# Generated by Django 4.2.4 on 2023-08-15 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wwg', '0003_rename_users_kakaousers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markings',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markings_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='records',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
