# Generated by Django 4.2.4 on 2023-08-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwg', '0003_alter_records_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='km',
            new_name='hours',
        ),
        migrations.RemoveField(
            model_name='records',
            name='TIME',
        ),
        migrations.AddField(
            model_name='records',
            name='kms',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_date',
            field=models.DateField(null=True),
        ),
    ]
