# Generated by Django 4.2.4 on 2023-08-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwg', '0005_delete_markings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saverecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='saverecord',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wwg.kakaousers'),
        ),
    ]
